### ISSUE TITLE
Segmentation fault at nex2img.f:356

### ISSUE THREAD

**Issue by akrherz** [Unidata/gempak#88]
I run `nex2img` routinely and a couple times per week observe "random" segfaults.  For posterity, this one yesterday with GEMPAK 7.14.0.1

```
#7  0x4784b9 in cfl_scandir
        at /home/akrherz/projects/gempak/gempak/source/gemlib/cfl/cflscandir.c:82
#8  0x474683 in cfl_scnt
        at /home/akrherz/projects/gempak/gempak/source/gemlib/cfl/cflscnt.c:64
#9  0x407aca in next_radar_
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/radar_grid.c:60
#10  0x405de4 in nex2img
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:241
#11  0x40654d in main
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:356
Segmentation fault (core dumped)
```

**Comment by akrherz** [comment]
another segfault to log
```
#8  0x46ecfa in crnexz
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gn/crnexz.c:251
#9  0x46c873 in wsatim_
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gif/wsatim.c:157
#10  0x46b1b1 in hsatim_
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gif/hsatim.f:62
#11  0x460b16 in dsatim_
        at /home/akrherz/projects/gempak/gempak/source/device/satellite/dsatim.f:42
#12  0x4448ca in gsatim_
        at /home/akrherz/projects/gempak/gempak/source/gplt/satellite/gsatim.f:72
#13  0x40d405 in im_drop_
        at /home/akrherz/projects/gempak/gempak/source/gemlib/im/imdrop.f:70
#14  0x405f46 in nex2img
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:270
#15  0x40654d in main
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:356
Abort (core dumped)
```

**Comment by akrherz** [comment]
and another

```
#9  0x46eba8 in crnexz
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gn/crnexz.c:199
#10  0x46c873 in wsatim_
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gif/wsatim.c:157
#11  0x46b1b1 in hsatim_
        at /home/akrherz/projects/gempak/gempak/source/driver/active/gif/hsatim.f:62
#12  0x460b16 in dsatim_
        at /home/akrherz/projects/gempak/gempak/source/device/satellite/dsatim.f:42
#13  0x4448ca in gsatim_
        at /home/akrherz/projects/gempak/gempak/source/gplt/satellite/gsatim.f:72
#14  0x40d405 in im_drop_
        at /home/akrherz/projects/gempak/gempak/source/gemlib/im/imdrop.f:70
#15  0x405f46 in nex2img
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:270
#16  0x40654d in main
        at /home/akrherz/projects/gempak/gempak/source/programs/upc/programs/nex2img/nex2img.f:356
Abort (core dumped)

```
